services:
  backend:
    build: .
    command: ["/app/webserver"]
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env.compose
    depends_on:
      - db
      - dragonfly

  initdb:
    build: .
    command: ["/app/initdb"]
    env_file:
      - .env.compose
    environment:
      - SQL_FILE=/app/db/CreateTables.sql
    depends_on:
      - backend

  dropdb:
    build: .
    command: ["/app/dropdb"]
    env_file:
      - .env.compose
    environment:
      - SQL_FILE=/app/db/DropTables.sql
    depends_on:
      - backend

  db:
    image: postgres:17.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME:-sguhack}
      - POSTGRES_USER=${DB_USER:-sguhack}
    env_file:
      - .env.compose
    healthcheck:
      test: "pg_isready --username=${DB_USER:-sguhack} --database=${DB_NAME:-sguhack}"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"] 
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
